### PR TITLE
Merge current dev to main

### PR DESCRIPTION
**Pull request by xperzy**
Most classification models now is able to train using single and multiple GPUs (Except BeiT and VOLO which needs other algorithms during training). So I open this PR and prepare a new version release for main branch.

### CODE REVIEW

**Review by lmk123568 — COMMENTED** [review]
LGTM，不过 crossvit 的图片需要小改一下，大致没问题哈

**Comment by lmk123568** [comment]
> LGTM，不过 crossvit 的图片需要小改一下，大致没问题哈

readme

**Review by cjh3020889729 — COMMENTED** [review]
LGTM

**Review by lmk123568 — APPROVED** [review]
np

**Review by cjh3020889729 — APPROVED** [review]

**Pull request merged**
