### PR TITLE
add(cvt): impl cvt for paddle

### PR DESCRIPTION
**Pull request by defensetongxue**
给paddle复现CvT论文。

### CODE REVIEW

**Review by lmk123568 — COMMENTED** [review]
非常棒！请问精度是否和官方对齐？我这边readme 没有看见相关的信息

**Comment by xperzy** [comment]
> 非常棒！请问精度是否和官方对齐？我这边readme 没有看见相关的信息

我正在改这部分，目前基本对齐，还需要进一步改代码风格和对齐更多模型@defensetongxue

**Comment by xperzy** [comment]
Now the cvt_13 ported weights obtains correct performance on Imagenet (81.60%).

There are still several issues should be finished before merging:
1. The implementations in cvt.py could be simplified, please refer to our ViT implementation ([here](https://github.com/BR-IDL/PaddleViT/blob/develop/image_classification/ViT/transformer.py))
2. Please convert more ported weights form the original repo and align the accuracies.
3. If possible, please also make the training settings same as the original paper.

**Comment by defensetongxue** [comment]
ok,i'll simplify the model soon

**Comment by defensetongxue** [comment]
I have  simplifed the code style and test the model cvt_13_384x384-1k(0.8275) and cvt_21_224x224-1k(0.8252).please check the code style if it can meet the requests ,thanks @xperzy

**Review by xperzy — APPROVED** [review]

**Comment by xperzy** [comment]
I have tested the performances and now the results are same as official repo.
So I merge this PR.

**Pull request merged**
