### PR TITLE
Add RandAugment in all model folders

### PR DESCRIPTION
**Pull request by skpig**
about issue https://github.com/BR-IDL/PaddleViT/issues/123.

### CODE REVIEW

**Comment by skpig** [comment]
For now, the PR is still in progress. I can't merge origin/develop because of issue https://github.com/BR-IDL/PaddleViT/issues/135.

**Comment by xperzy** [comment]
A New PR #137 is submitted for issue #135.

**Comment by skpig** [comment]
The PR is now ready to be merged.
@xperzy Please review my code. Thank you!

**Review by xperzy — APPROVED** [review]

**Comment by xperzy** [comment]
Nice Work ! LTGM

**Pull request merged**
